apiVersion: v1
kind: ServiceAccount
metadata:
  name: personal-project-sa
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: personal-project-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: personal-project-rolebinding
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: personal-project-sa
  namespace: argocd
roleRef:
  kind: Role
  name: personal-project-role
  apiGroup: rbac.authorization.k8s.io