pipeline {
    agent any
    environment{
        APP_NAME = "personalproject"
        IMAGE_TAG = "v1.0.${BUILD_NUMBER}"
    }
    options {timestamps()}
    triggers { githubPush() } // triggers pipeline on GitHub push events
    stages {
        stage('Checkout') {
            steps {
                script {
                    def skip = sh(script: "git log -1 --pretty=%B | grep -i '\\[ci skip\\]\\|\\[skip ci\\]'", returnStatus: true) == 0
                    if (skip) {
                        echo "Skipping build due to commit message."
                        currentBuild.result = 'SUCCESS'
                        // This will stop the pipeline early
                        return
                    }
                    //Checkout the code from the repository
                    checkout scm
                }
            }
        }
        stage('Run Unit Tests') {
            steps {
            sh '''
                echo "Running Unit Tests..."
                docker run --rm -v $PWD/Week02/flask-app:/app -w /app flask-app:latest \
                /bin/bash -c "pytest tests.py --junitxml=test-results/results.xml"
            '''
            }
        }
        stage('Build Docker image') {
            when{ 
                branch 'main' 
                expression {return fileExists('Week02/flask-app/Dockerfile')}
            }
            steps {
                withCredentials([azureServicePrincipal('AZURE_CONTAINER_REGISTRY')]) {
                sh '''
                echo "Building Docker Image..."
                cd Week02/flask-app
                docker build -t $AZURE_TENANT_ID/$APP_NAME:$IMAGE_TAG .
                '''
                }
            }
        }
        stage('Push to Registry') {
            when{branch 'main'}
            steps {
                withCredentials([azureServicePrincipal('AZURE_CONTAINER_REGISTRY')]) {
                sh '''
                echo "Pushing Docker Image to Registry..."
                echo $AZURE_CLIENT_SECRET | docker login $AZURE_TENANT_ID -u $AZURE_CLIENT_ID --password-stdin
                docker push $AZURE_TENANT_ID/$APP_NAME:$IMAGE_TAG
                '''
                }
            }
        }
        stage('Update Kubernetes Deployment') {
            when { branch 'main' }
            steps {
                withCredentials([azureServicePrincipal('AZURE_CONTAINER_REGISTRY'), gitUsernamePassword(credentialsId: 'seniorprojecttoken', gitToolName: '')]) {
                    sh '''
                    echo "Updating deployment manifest with new image tag..."
                    cd Week02/infra
                    echo "CURRENT DEPLOYMENT MANIFEST:"
                    cat deployment.yaml
                    sed -i "s|image:.*|image: $AZURE_TENANT_ID/$APP_NAME:$IMAGE_TAG|g" deployment.yaml
                    echo "UPDATED DEPLOYMENT MANIFEST:"
                    cat deployment.yaml
                    echo "Pushing updated manifest to GitHub repository..."

                    git config --global user.name "ci-bot"
                    git config --global user.email "ci-bot@example.com"
                    git remote set-url origin https://$GIT_USERNAME:$GIT_PASSWORD@github.com/EnitanM/CI-CD.git

                    #Ensure this is the main branch
                    git checkout main
                    git pull origin main

                    git add deployment.yaml
                    git commit -m "Updated deployment image to $IMAGE_TAG [ci skip]"
                    git push origin main
                    '''
                }
            }
        }
    }
    post {
        always {
                junit 'Week02/flask-app/test-results/results.xml'
                archiveArtifacts artifacts: '**/test-results/*.xml', allowEmptyArchive: true
            cleanWs()
        }
    }
}