pipeline {
    agent any
    environment{
        APP_NAME = "personalproject"
        IMAGE_TAG = "v1.0.${BUILD_NUMBER}"
    }
    options {timestamps()}
    triggers { githubPush() } // triggers pipeline on GitHub push events
    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the repository
                checkout scm
            }
        }
        stage('Installing Dependencies') {
            steps {
            sh '''
                echo "Installing dependencies inside Docker container..."
                docker run --rm -v $PWD/Week02/flask-app:/app -w /app flask-app:latest \
                /bin/bash -c "python3 -m venv venv && . venv/bin/activate"
            '''
            }
        }
        stage('Run Unit Tests') {
            steps {
            sh '''
                echo "Running Unit Tests..."
                docker run --rm -v $PWD/Week02/flask-app:/app -w /app flask-app:latest \
                /bin/bash -c "pytest tests.py --junitxml=test-results/results.xml"
            '''
            }
        }
        stage('Build Docker image') {
            when{expression {return fileExists('Week02/flask-app/Dockerfile')}}
            steps {
                withCredentials([azureServicePrincipal('AZURE_CONTAINER_REGISTRY')]) {
                sh '''
                echo "Building Docker Image..."
                cd Week02/flask-app
                docker build -t $AZURE_TENANT_ID/$APP_NAME:$IMAGE_TAG .
                '''
                }
            }
        }
        stage('Push to Registry') {
            when{branch 'main'}
            steps {
                withCredentials([azureServicePrincipal('AZURE_CONTAINER_REGISTRY')]) {
                sh '''
                echo "Pushing Docker Image to Registry..."
                echo $AZURE_CLIENT_SECRET | docker login $AZURE_TENANT_ID -u $AZURE_CLIENT_ID --password-stdin
                docker push $AZURE_TENANT_ID/$APP_NAME:$IMAGE_TAG
                '''
                }
            }
        }
        stage('Deploy to Kubernetes') {
            when { branch 'main' }
            steps {
                withCredentials([azureServicePrincipal('AZURE_CONTAINER_REGISTRY')]) {
                    sh '''
                    echo "Updating deployment manifest with current image tag..."
                    export IMAGE_TAG=v1.0.${BUILD_NUMBER}
                    export IMAGE_NAME=capstoneteam1-avd2dagya7gjdhda.azurecr.io/personalproject:$IMAGE_TAG

                    # Substitute the image tag in the deployment manifest
                    envsubst < Week02/infra/deployment.yaml > Week02/infra/deployment.generated.yaml

                    echo "Applying updated manifest to Kubernetes..."
                    kubectl apply -f Week02/infra/deployment.generated.yaml
                    '''
                }
            }
        }
    }
    post {
        always {
                junit 'Week02/flask-app/test-results/results.xml'
            cleanWs()
        }
    }
}