pipeline {
    agent {
        docker {
            image 'docker:latest'
        }
    }
    environment{
        APP_NAME = "personalproject"
        IMAGE_TAG = "v2.0.${BUILD_NUMBER}"
        DOCKER_IMAGE = "${APP_NAME}"
        DOCKER_REGISTRY = "enitanm"
    }
    options {timestamps()}
    triggers { githubPush() }
    stages {
        stage('Checkout') {
            steps {
                scmSkip(deleteBuild: true)
                checkout scm
            }
        }
        stage('Run Unit Tests') {
            when{ 
                expression { fileExists('src/flask-app/Dockerfile')}
            }
            steps {
                sh '''
                    echo "Building Docker image for unit tests..."
                    cd src/flask-app
                    docker build -t $DOCKER_IMAGE .
                '''
                sh '''
                echo "Running Unit Tests..."
                docker run --rm -v $PWD/src/flask-app:/app -w /app $DOCKER_IMAGE \
                /bin/bash -c "pytest tests.py --junitxml=test-results/results.xml"
                '''
            }
        }
        stage('Run Security Scans') {
            steps {
                sh '''
                echo "Scanning Docker image with Trivy..."
                if ! command -v trivy > /dev/null; then
                echo "Installing Trivy..."
                mkdir -p $HOME/bin
                curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $HOME/bin
                fi
                export PATH="$HOME/bin:$PATH"
                mkdir -p Reports
                trivy image --exit-code 1 --severity HIGH,CRITICAL --format table $DOCKER_IMAGE | tee Reports/trivy-report.txt
                '''
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
                    sh '''
                    echo "Scanning Docker image with Docker Scout..."
                    if ! command -v scout > /dev/null; then
                    echo "Installing Docker Scout..."
                    curl -sfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s -- -b $HOME/bin
                    fi
                    export PATH="$HOME/bin:$PATH"
                    mkdir -p Reports
                    echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
                    docker-scout cves $DOCKER_IMAGE:latest --exit-code --only-severity critical,high --format markdown | tee Reports/scout-report.md
                    '''
                }
            }
        } 
        stage('Push to Registry') {
            when { branch 'main' }
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
                    sh '''
                    echo "Pushing Docker Image to Registry..."
                    echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
                    docker tag $DOCKER_IMAGE $DOCKER_REGISTRY/$APP_NAME:$IMAGE_TAG
                    docker push $DOCKER_REGISTRY/$APP_NAME:$IMAGE_TAG
                    '''
                }
            }
        }
        stage('Update Kubernetes Deployment') {
            when { branch 'main' }
            steps {
                withCredentials([gitUsernamePassword(credentialsId: 'seniorprojecttoken', gitToolName: '')]) {
                    sh '''
                    echo "Updating deployment manifest with new image tag..."
                    cd src/infra/helm/flask-app
                    echo "CURRENT VALUES MANIFEST:"
                    cat values.yaml
                    sed -i "s|tag:.*|tag: ${IMAGE_TAG}|g" values.yaml
                    echo "UPDATED VALUES MANIFEST:"
                    cat values.yaml
                    echo "Pushing updated manifest to GitHub repository..."

                    git remote set-url origin https://$GIT_USERNAME:$GIT_PASSWORD@github.com/EnitanM/CI-CD.git

                    #Ensure this is the main branch
                    git checkout main
                    git pull origin main
                    git add values.yaml
                    git commit -m "Updated image tag to $IMAGE_TAG [ci skip]"
                    git push origin main
                    '''
                }
            }
        }
    }
    post {
        always {
            junit 'src/flask-app/test-results/results.xml'
            archiveArtifacts artifacts: 'Reports/trivy-report.txt', allowEmptyArchive: true
            archiveArtifacts artifacts: 'Reports/scout-report.md', allowEmptyArchive: true
            cleanWs()
        }
    }
}